from haskell-dev

run dnf install -y alex happy wget cabal-install zlib-devel ncurses-static.x86_64 #libtinfo-dev

run cabal update && cabal install cabal-install

run cabal install idris

run cd ~/.vim/bundle && git clone https://github.com/idris-hackers/idris-vim.git
